name: taush
description: A TechGenesis project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  country_picker: ^2.0.20
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  provider: ^6.0.5
  fluttertoast: ^8.2.2
  page_transition: ^2.0.9
  persistent_bottom_nav_bar_v2: ^5.3.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.6
  uuid: ^4.5.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  flutter_rating_bar: ^4.0.1
  razorpay_flutter: ^1.3.5
  motion_toast: ^2.6.8
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/carousel_slideshow/
    - assets/images/categories/
    - assets/images/offersNsponcered/
    - assets/images/todays_deals/
    - assets/images/menu_pics/
    - assets/videos/
