// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk2k6GiYRI5qE1cvUGk89Gk8UMmd1aWdQ',
    appId: '1:813698886284:android:abb05e6493f70ece7fa9a9',
    messagingSenderId: '813698886284',
    projectId: 'taush-313db',
    storageBucket: 'taush-313db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAOnM8ClrHN-3s_Hyxqev1N3_W-uveE1o',
    appId: '1:813698886284:ios:642e8f408df6457f7fa9a9',
    messagingSenderId: '813698886284',
    projectId: 'taush-313db',
    storageBucket: 'taush-313db.firebasestorage.app',
    iosBundleId: 'com.example.taush',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAwfIAnU3ZlvP5OgE_ucFv_LXbPu8SnHg',
    appId: '1:813698886284:web:a5dc4453757fb56b7fa9a9',
    messagingSenderId: '813698886284',
    projectId: 'taush-313db',
    authDomain: 'taush-313db.firebaseapp.com',
    storageBucket: 'taush-313db.firebasestorage.app',
    measurementId: 'G-99L6KYT9YB',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAOnM8ClrHN-3s_Hyxqev1N3_W-uveE1o',
    appId: '1:813698886284:ios:642e8f408df6457f7fa9a9',
    messagingSenderId: '813698886284',
    projectId: 'taush-313db',
    storageBucket: 'taush-313db.firebasestorage.app',
    iosBundleId: 'com.example.taush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAwfIAnU3ZlvP5OgE_ucFv_LXbPu8SnHg',
    appId: '1:813698886284:web:3c841a49af926b557fa9a9',
    messagingSenderId: '813698886284',
    projectId: 'taush-313db',
    authDomain: 'taush-313db.firebaseapp.com',
    storageBucket: 'taush-313db.firebasestorage.app',
    measurementId: 'G-TR6EYCT84Z',
  );

}